### ISSUE TITLE
Can't start the service

### ISSUE THREAD

**Issue by wes1993** [pgross41/dvr163#8]
Hello,
Thanks for your project.
I can't start the service, from docker inside the scripts:
/usr/src/app/dist/config.js:17
        throw Error(error);
        ^

Error: Missing required environment variable: NVR_HOST
    at required.forEach (/usr/src/app/dist/config.js:17:15)
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/usr/src/app/dist/config.js:14:10)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)

Where i need to write the variable?
from npm:
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.8
3 info using node@v12.18.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle dvr163@1.0.0~prestart: dvr163@1.0.0
6 verbose lifecycle dvr163@1.0.0~prestart: unsafe-perm in lifecycle true
7 verbose lifecycle dvr163@1.0.0~prestart: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/dvr163/dvr163/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/s
bin:/bin:/usr/games:/usr/local/games:/usr/local/cuda-9.1/bin:/opt/ffmpeg/bin:/snap/bin
8 verbose lifecycle dvr163@1.0.0~prestart: CWD: /home/dvr163/dvr163
9 silly lifecycle dvr163@1.0.0~prestart: Args: [ '-c', 'npm run build' ]
10 silly lifecycle dvr163@1.0.0~prestart: Returned: code: 1  signal: null
11 info lifecycle dvr163@1.0.0~prestart: Failed to exec prestart script
12 verbose stack Error: dvr163@1.0.0 prestart: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:315:20)
12 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:315:20)
12 verbose stack     at maybeClose (internal/child_process.js:1021:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
13 verbose pkgid dvr163@1.0.0
14 verbose cwd /home/dvr163/dvr163
15 verbose Linux 4.15.0-117-generic
16 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "start"
17 verbose node v12.18.4
18 verbose npm  v6.14.8
19 error code ELIFECYCLE
20 error errno 1
21 error dvr163@1.0.0 prestart: `npm run build`
21 error Exit status 1
22 error Failed at the dvr163@1.0.0 prestart script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

Thnanks a lot for your help

**Comment by pgross41** [comment]
Hi @wes1993 I haven't looked at this project in a while but it looks like you need to provide the required environment variables. See [.env.example](https://github.com/pgross41/dvr163/blob/master/.env.example) for an example environment variable file. 

You can pass that file into the `docker run` command with the `--env-file` argument. Example: 
```
docker run --rm --name=dvr163 --env-file=.env -p 8889:8889 pgross41/dvr163:2.0.0
```

I no longer use this project because I just use Home Assistant (even though the video is choppy). Someday I will likely add the streaming functionality into the [add-on](https://github.com/pgross41/hassio-addons/tree/main/dvr163) but that is not prioritized at the moment.

**Comment by wes1993** [comment]
Thanks a lot for your reply :-D
I have finally executed the container but unfortunately is not compatible with my version of NVR firmware.
Thanks again a lot for your Help :-D
Regards
Stefano
